services:
  aui-backend:

    container_name: aui-backend

    restart: always
    image: ghcr.io/mattiarainieri/aui-backend:latest
    networks:
      aui-internal:
        aliases:
          - aui-backend



networks:
  aui-internal:
    name: aui-internal
    external: true